# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoadStartImgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LoadStartImgBtn.setGeometry(QtCore.QRect(50, 10, 171, 31))
        self.LoadStartImgBtn.setObjectName("LoadStartImgBtn")
        self.LoadEndImgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LoadEndImgBtn.setGeometry(QtCore.QRect(710, 10, 161, 31))
        self.LoadEndImgBtn.setObjectName("LoadEndImgBtn")
        self.BlendingRateBar = QtWidgets.QSlider(self.centralwidget)
        self.BlendingRateBar.setEnabled(False)
        self.BlendingRateBar.setGeometry(QtCore.QRect(190, 360, 591, 22))
        self.BlendingRateBar.setMaximum(100)
        self.BlendingRateBar.setSingleStep(5)
        self.BlendingRateBar.setPageStep(5)
        self.BlendingRateBar.setProperty("value", 0)
        self.BlendingRateBar.setOrientation(QtCore.Qt.Horizontal)
        self.BlendingRateBar.setObjectName("BlendingRateBar")
        self.Alphalabel = QtWidgets.QLabel(self.centralwidget)
        self.Alphalabel.setGeometry(QtCore.QRect(136, 370, 51, 20))
        self.Alphalabel.setObjectName("Alphalabel")
        self.zero = QtWidgets.QLabel(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(190, 390, 61, 31))
        self.zero.setObjectName("zero")
        self.StartImgName = QtWidgets.QLabel(self.centralwidget)
        self.StartImgName.setGeometry(QtCore.QRect(170, 320, 101, 31))
        self.StartImgName.setObjectName("StartImgName")
        self.EndImgName = QtWidgets.QLabel(self.centralwidget)
        self.EndImgName.setGeometry(QtCore.QRect(730, 320, 91, 31))
        self.EndImgName.setObjectName("EndImgName")
        self.TriDisplayBox = QtWidgets.QCheckBox(self.centralwidget)
        self.TriDisplayBox.setGeometry(QtCore.QRect(450, 320, 121, 31))
        self.TriDisplayBox.setObjectName("TriDisplayBox")
        self.StartImgCanvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.StartImgCanvas.setGeometry(QtCore.QRect(50, 50, 360, 270))
        self.StartImgCanvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StartImgCanvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StartImgCanvas.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.StartImgCanvas.setObjectName("StartImgCanvas")
        self.BlendedImgCanvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.BlendedImgCanvas.setGeometry(QtCore.QRect(320, 390, 360, 270))
        self.BlendedImgCanvas.setObjectName("BlendedImgCanvas")
        self.one = QtWidgets.QLabel(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(770, 400, 61, 31))
        self.one.setObjectName("one")
        self.BlendName = QtWidgets.QLabel(self.centralwidget)
        self.BlendName.setGeometry(QtCore.QRect(470, 680, 101, 31))
        self.BlendName.setObjectName("BlendName")
        self.alphaBox = QtWidgets.QTextEdit(self.centralwidget)
        self.alphaBox.setEnabled(False)
        self.alphaBox.setGeometry(QtCore.QRect(810, 360, 51, 31))
        self.alphaBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.alphaBox.setPlaceholderText("")
        self.alphaBox.setObjectName("alphaBox")
        self.BlendButton = QtWidgets.QPushButton(self.centralwidget)
        self.BlendButton.setEnabled(False)
        self.BlendButton.setGeometry(QtCore.QRect(480, 710, 75, 23))
        self.BlendButton.setObjectName("BlendButton")
        self.EndImgCanvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.EndImgCanvas.setGeometry(QtCore.QRect(600, 50, 360, 270))
        self.EndImgCanvas.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.EndImgCanvas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.EndImgCanvas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.EndImgCanvas.setObjectName("EndImgCanvas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadStartImgBtn.setText(_translate("MainWindow", "Load Starting Image"))
        self.LoadEndImgBtn.setText(_translate("MainWindow", "Load Ending Image"))
        self.Alphalabel.setText(_translate("MainWindow", "Alpha"))
        self.zero.setText(_translate("MainWindow", "0.0"))
        self.StartImgName.setText(_translate("MainWindow", "Starting Image"))
        self.EndImgName.setText(_translate("MainWindow", "Ending Image"))
        self.TriDisplayBox.setText(_translate("MainWindow", "show Traigles"))
        self.one.setText(_translate("MainWindow", "1.0"))
        self.BlendName.setText(_translate("MainWindow", "Blending Image"))
        self.BlendButton.setText(_translate("MainWindow", "Blend"))


